### ISSUE TITLE
HashMap - null.

### ISSUE THREAD

**Issue by Therealnaxos** [Rasmus1989/Projektarebete_Grupp2#1]
När vi hämtar hashmap innehållandes en String och int, får vi ut null. Där finns värden, syns på Firebase.

**Comment by Therealnaxos** [comment]
if (dataSnapshot.getKey().equals("four")){
                         Map<String, Object> newPost = (Map<String, Object>) arg0.getValue();
                         System.out.println("Answer: " + newPost.get("alternative"));
                         System.out.println("Votes: " + newPost.get("votes"));
                     }

Detta returnerar, "null", "null".

**Comment by k3larra** [comment]
@Therealnaxos  var är detta? Vilken fil vilket projekt?

**Comment by Therealnaxos** [comment]
@k3larra Vi har två nya repos, där vi har separerat android & eclipse.

här är filen:

https://github.com/Bankmongot/Pfi3_Projektarbete_Grupp2_Desktop/blob/master/ScreenSwing/src/se/mah/k3/FireBase.java

**Comment by k3larra** [comment]
Och hur återskapar jag ert fel?
